pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/RachappaB/system-admin-.git'
            }
        }

        stage('Build Image') {
            steps {
                dir('jenkins') {
                    sh 'docker build -t node-ci-demo .'
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh 'docker rm -f nodeapp || true'
            }
        }

        stage('Deploy New Container') {
            steps {
                dir('jenkins') {
                    sh 'docker run -d -p 3000:3000 --name nodeapp node-ci-demo'
                }
            }
        }

    }
}
